/**
 * Unit Tests: GPX Generation & Route Statistics
 * Tests GPX XML generation, route stats calculations, and simplification
 */

import { describe, it, expect } from 'vitest';
import { generateGPX, calculateRouteStats, simplifyRoute } from '../../src/utils/gpx.js';

describe('GPX Generation', () => {
  describe('generateGPX()', () => {
    it('should generate valid GPX XML with basic waypoints', () => {
      const waypoints = [
        { lat: 49.48333, lng: 18.23333, elevation: 1000 },
        { lat: 49.48889, lng: 18.21389, elevation: 1129 },
      ];

      const gpx = generateGPX(waypoints);

      expect(gpx).toContain('<?xml version="1.0" encoding="UTF-8"?>');
      expect(gpx).toContain('<gpx version="1.1"');
      expect(gpx).toContain('creator="Hike AI - https://hikeai.app"');
      expect(gpx).toContain('<trk>');
      expect(gpx).toContain('<trkpt lat="49.48333" lon="18.23333">');
      expect(gpx).toContain('<trkpt lat="49.48889" lon="18.21389">');
      expect(gpx).toContain('<ele>1000</ele>');
      expect(gpx).toContain('<ele>1129</ele>');
      expect(gpx).toContain('</gpx>');
    });

    it('should include metadata in GPX output', () => {
      const waypoints = [{ lat: 50.0, lng: 15.0 }];
      const metadata = {
        name: 'Test Route',
        description: 'A test hiking route',
        author: 'Test Author',
      };

      const gpx = generateGPX(waypoints, [], metadata);

      expect(gpx).toContain('<name>Test Route</name>');
      expect(gpx).toContain('<desc>A test hiking route</desc>');
      expect(gpx).toContain('<author>');
      expect(gpx).toContain('<name>Test Author</name>');
      expect(gpx).toContain('<time>');
    });

    it('should escape XML special characters in metadata', () => {
      const waypoints = [{ lat: 50.0, lng: 15.0 }];
      const metadata = {
        name: 'Route <with> "special" & \'chars\'',
        description: 'Testing & validation',
      };

      const gpx = generateGPX(waypoints, [], metadata);

      // XML special chars should be escaped
      expect(gpx).toContain('&lt;with&gt;');
      expect(gpx).toContain('&quot;special&quot;');
      expect(gpx).toContain('&amp;');
      expect(gpx).toContain('&apos;chars&apos;');
      expect(gpx).toContain('Testing &amp; validation');
    });

    it('should include POIs as waypoints in GPX', () => {
      const waypoints = [
        { lat: 49.48333, lng: 18.23333 },
        { lat: 49.48889, lng: 18.21389 },
      ];
      const pois = [
        {
          name: 'Radhošť',
          lat: 49.48889,
          lng: 18.21389,
          type: 'peak',
          elevation: 1129,
          description: 'Famous Beskydy peak',
        },
      ];

      const gpx = generateGPX(waypoints, pois);

      expect(gpx).toContain('<wpt lat="49.48889" lon="18.21389">');
      expect(gpx).toContain('<name>Radhošť</name>');
      expect(gpx).toContain('<type>peak</type>');
      expect(gpx).toContain('<ele>1129</ele>');
      expect(gpx).toContain('<desc>Famous Beskydy peak</desc>');
    });

    it('should handle waypoints without elevation data', () => {
      const waypoints = [
        { lat: 49.48333, lng: 18.23333 }, // No elevation
        { lat: 49.48889, lng: 18.21389, elevation: 1129 },
      ];

      const gpx = generateGPX(waypoints);

      // First waypoint should NOT have <ele> tag
      const firstTrkpt = gpx.match(/<trkpt lat="49.48333"[^>]*>[\s\S]*?<\/trkpt>/)[0];
      expect(firstTrkpt).not.toContain('<ele>');

      // Second waypoint SHOULD have <ele> tag
      expect(gpx).toContain('<ele>1129</ele>');
    });

    it('should use default metadata when not provided', () => {
      const waypoints = [{ lat: 50.0, lng: 15.0 }];

      const gpx = generateGPX(waypoints);

      expect(gpx).toContain('<name>Hike AI Route</name>');
      expect(gpx).toContain('<desc>Generated by Hike AI</desc>');
      expect(gpx).toContain('<name>Hike AI</name>'); // Default author
    });

    it('should handle empty POIs array gracefully', () => {
      const waypoints = [{ lat: 50.0, lng: 15.0 }];

      const gpx = generateGPX(waypoints, []);

      expect(gpx).toContain('<gpx');
      expect(gpx).not.toContain('<wpt'); // No waypoint markers
      expect(gpx).toContain('<trk>'); // Track should still exist
    });
  });

  describe('calculateRouteStats()', () => {
    it('should calculate total distance from waypoints', () => {
      // Pustevny to Radhošť (actual air distance ~1.5km)
      const waypoints = [
        { lat: 49.48333, lng: 18.23333 },
        { lat: 49.48889, lng: 18.21389 },
      ];

      const stats = calculateRouteStats(waypoints);

      expect(stats.distance).toBeGreaterThan(1); // > 1km
      expect(stats.distance).toBeLessThan(2); // < 2km
    });

    it('should calculate elevation gain correctly', () => {
      const waypoints = [
        { lat: 50.0, lng: 15.0, elevation: 500 },
        { lat: 50.01, lng: 15.01, elevation: 600 }, // +100m
        { lat: 50.02, lng: 15.02, elevation: 750 }, // +150m
      ];

      const stats = calculateRouteStats(waypoints);

      expect(stats.elevationGain).toBe(250); // 100 + 150
    });

    it('should calculate elevation loss correctly', () => {
      const waypoints = [
        { lat: 50.0, lng: 15.0, elevation: 1000 },
        { lat: 50.01, lng: 15.01, elevation: 900 }, // -100m
        { lat: 50.02, lng: 15.02, elevation: 750 }, // -150m
      ];

      const stats = calculateRouteStats(waypoints);

      expect(stats.elevationLoss).toBe(250); // 100 + 150
    });

    it('should calculate elevation gain and loss separately', () => {
      const waypoints = [
        { lat: 50.0, lng: 15.0, elevation: 500 },
        { lat: 50.01, lng: 15.01, elevation: 700 }, // +200m
        { lat: 50.02, lng: 15.02, elevation: 600 }, // -100m
        { lat: 50.03, lng: 15.03, elevation: 800 }, // +200m
      ];

      const stats = calculateRouteStats(waypoints);

      expect(stats.elevationGain).toBe(400); // 200 + 200
      expect(stats.elevationLoss).toBe(100); // 100
    });

    it('should estimate duration using Naismith rule', () => {
      // 5 km flat + 600m elevation gain = ~2 hours
      const waypoints = [
        { lat: 50.0, lng: 15.0, elevation: 500 },
        { lat: 50.045, lng: 15.0, elevation: 1100 }, // ~5km + 600m gain
      ];

      const stats = calculateRouteStats(waypoints);

      // Base time: 5km / 5km/h = 1h
      // Elevation time: 600m / 600m/h = 1h
      // Total: ~2h
      expect(stats.estimatedDuration).toBeGreaterThan(1.5);
      expect(stats.estimatedDuration).toBeLessThan(2.5);
    });

    it('should return zeros for empty waypoints array', () => {
      const stats = calculateRouteStats([]);

      expect(stats.distance).toBe(0);
      expect(stats.elevationGain).toBe(0);
      expect(stats.elevationLoss).toBe(0);
      expect(stats.estimatedDuration).toBe(0);
    });

    it('should return zeros for single waypoint', () => {
      const stats = calculateRouteStats([{ lat: 50.0, lng: 15.0, elevation: 1000 }]);

      expect(stats.distance).toBe(0);
      expect(stats.elevationGain).toBe(0);
      expect(stats.elevationLoss).toBe(0);
      expect(stats.estimatedDuration).toBe(0);
    });

    it('should handle waypoints without elevation data gracefully', () => {
      const waypoints = [
        { lat: 50.0, lng: 15.0 }, // No elevation
        { lat: 50.01, lng: 15.01 }, // No elevation
      ];

      const stats = calculateRouteStats(waypoints);

      expect(stats.distance).toBeGreaterThan(0); // Distance calculated
      expect(stats.elevationGain).toBe(0); // No elevation data
      expect(stats.elevationLoss).toBe(0);
    });
  });

  describe('simplifyRoute()', () => {
    it('should return same waypoints if <= 2 points', () => {
      const waypoints = [
        { lat: 50.0, lng: 15.0 },
        { lat: 50.01, lng: 15.01 },
      ];

      const simplified = simplifyRoute(waypoints, 0.01);

      expect(simplified).toEqual(waypoints);
      expect(simplified.length).toBe(2);
    });

    it('should simplify route using Douglas-Peucker algorithm', () => {
      // Create a straight line with a slight detour in the middle
      const waypoints = [
        { lat: 50.0, lng: 15.0 },
        { lat: 50.005, lng: 15.005 }, // Middle point close to line
        { lat: 50.01, lng: 15.01 },
      ];

      // Low tolerance should keep all points (simplified implementation uses min distance)
      const simplified = simplifyRoute(waypoints, 0.001);

      expect(simplified.length).toBeGreaterThanOrEqual(2);
      expect(simplified[0]).toEqual(waypoints[0]);
    });

    it('should keep significant waypoints with low tolerance', () => {
      // Create a route with a significant detour
      const waypoints = [
        { lat: 50.0, lng: 15.0 },
        { lat: 50.01, lng: 15.0 }, // Significant detour
        { lat: 50.01, lng: 15.01 },
      ];

      // Low tolerance should keep all points
      const simplified = simplifyRoute(waypoints, 0.001);

      expect(simplified.length).toBeGreaterThan(2);
    });
  });
});
