/**
 * GPX Generation Utility
 * Converts route data to GPX (GPS Exchange Format) XML
 */

/**
 * Generate GPX XML from route data
 * @param {Array<Object>} waypoints - Array of {lat, lng, elevation?}
 * @param {Array<Object>} pois - Array of POIs {name, lat, lng, type, description}
 * @param {Object} metadata - Route metadata {name, description, author}
 * @returns {string} - GPX XML string
 */
export function generateGPX(waypoints, pois = [], metadata = {}) {
  const name = metadata.name || 'Hike AI Route';
  const description = metadata.description || 'Generated by Hike AI';
  const author = metadata.author || 'Hike AI';
  const timestamp = new Date().toISOString();

  let gpx = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1"
     creator="Hike AI - https://hikeai.app"
     xmlns="http://www.topografix.com/GPX/1/1"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">

  <metadata>
    <name>${escapeXml(name)}</name>
    <desc>${escapeXml(description)}</desc>
    <author>
      <name>${escapeXml(author)}</name>
    </author>
    <time>${timestamp}</time>
  </metadata>

`;

  // Add POIs as waypoints
  if (pois && pois.length > 0) {
    pois.forEach((poi) => {
      gpx += `  <wpt lat="${poi.lat}" lon="${poi.lng}">
    <name>${escapeXml(poi.name)}</name>
    ${poi.elevation ? `<ele>${poi.elevation}</ele>` : ''}
    <type>${escapeXml(poi.type || 'poi')}</type>
    ${poi.description ? `<desc>${escapeXml(poi.description)}</desc>` : ''}
  </wpt>
`;
    });
  }

  // Add route track
  gpx += `  <trk>
    <name>${escapeXml(name)}</name>
    <desc>${escapeXml(description)}</desc>
    <trkseg>
`;

  // Add all waypoints as track points
  waypoints.forEach((point) => {
    gpx += `      <trkpt lat="${point.lat}" lon="${point.lng}">
        ${point.elevation ? `<ele>${point.elevation}</ele>` : ''}
      </trkpt>
`;
  });

  gpx += `    </trkseg>
  </trk>

</gpx>`;

  return gpx;
}

/**
 * Escape XML special characters
 * @param {string} text
 * @returns {string}
 */
function escapeXml(text) {
  if (!text) return '';

  return text
    .toString()
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Calculate route statistics from waypoints
 * @param {Array<Object>} waypoints - Array of {lat, lng, elevation?}
 * @returns {Object} - {distance, elevationGain, elevationLoss, duration}
 */
export function calculateRouteStats(waypoints) {
  if (!waypoints || waypoints.length < 2) {
    return {
      distance: 0,
      elevationGain: 0,
      elevationLoss: 0,
      estimatedDuration: 0,
    };
  }

  let totalDistance = 0;
  let elevationGain = 0;
  let elevationLoss = 0;

  for (let i = 1; i < waypoints.length; i++) {
    const prev = waypoints[i - 1];
    const curr = waypoints[i];

    // Calculate distance between points
    const dist = haversineDistance(prev.lat, prev.lng, curr.lat, curr.lng);
    totalDistance += dist;

    // Calculate elevation change
    if (prev.elevation && curr.elevation) {
      const elevChange = curr.elevation - prev.elevation;
      if (elevChange > 0) {
        elevationGain += elevChange;
      } else {
        elevationLoss += Math.abs(elevChange);
      }
    }
  }

  // Estimate duration (Naismith's rule + adjustments)
  // Base: 5 km/h on flat terrain
  // Add: 1 hour per 600m elevation gain
  const baseTime = totalDistance / 5; // hours
  const elevationTime = elevationGain / 600; // hours
  const estimatedDuration = baseTime + elevationTime;

  return {
    distance: Math.round(totalDistance * 100) / 100, // Round to 2 decimals
    elevationGain: Math.round(elevationGain),
    elevationLoss: Math.round(elevationLoss),
    estimatedDuration: Math.round(estimatedDuration * 10) / 10, // Round to 1 decimal
  };
}

/**
 * Haversine formula for distance between two points
 * @param {number} lat1
 * @param {number} lng1
 * @param {number} lat2
 * @param {number} lng2
 * @returns {number} - Distance in kilometers
 */
function haversineDistance(lat1, lng1, lat2, lng2) {
  const R = 6371; // Earth radius in km
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);

  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(toRad(lat1)) *
      Math.cos(toRad(lat2)) *
      Math.sin(dLng / 2) *
      Math.sin(dLng / 2);

  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

/**
 * Convert degrees to radians
 * @param {number} degrees
 * @returns {number}
 */
function toRad(degrees) {
  return (degrees * Math.PI) / 180;
}

/**
 * Simplify route by reducing waypoints (Douglas-Peucker algorithm)
 * Useful for reducing GPX file size
 * @param {Array<Object>} waypoints
 * @param {number} tolerance - Distance tolerance in km
 * @returns {Array<Object>}
 */
export function simplifyRoute(waypoints, tolerance = 0.01) {
  if (waypoints.length <= 2) return waypoints;

  // Douglas-Peucker algorithm implementation
  let maxDistance = 0;
  let maxIndex = 0;

  const first = waypoints[0];
  const last = waypoints[waypoints.length - 1];

  for (let i = 1; i < waypoints.length - 1; i++) {
    const distance = perpendicularDistance(waypoints[i], first, last);
    if (distance > maxDistance) {
      maxDistance = distance;
      maxIndex = i;
    }
  }

  if (maxDistance > tolerance) {
    const left = simplifyRoute(waypoints.slice(0, maxIndex + 1), tolerance);
    const right = simplifyRoute(waypoints.slice(maxIndex), tolerance);
    return [...left.slice(0, -1), ...right];
  } else {
    return [first, last];
  }
}

/**
 * Calculate perpendicular distance from point to line
 * @param {Object} point - {lat, lng}
 * @param {Object} lineStart - {lat, lng}
 * @param {Object} lineEnd - {lat, lng}
 * @returns {number} - Distance in km
 */
function perpendicularDistance(point, lineStart, lineEnd) {
  // Simplified version using haversine distance
  const distToStart = haversineDistance(
    point.lat,
    point.lng,
    lineStart.lat,
    lineStart.lng
  );
  const distToEnd = haversineDistance(
    point.lat,
    point.lng,
    lineEnd.lat,
    lineEnd.lng
  );
  return Math.min(distToStart, distToEnd);
}

export default {
  generateGPX,
  calculateRouteStats,
  simplifyRoute,
};
